# --- q_adv specific parameters ---

# use epsilon greedy action selector
# action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 3000000 #2004000
fc : "CNN"
# mac: cqmix_mac

# runner: "episode"

# buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
# agent_output_type: "q"
learner_q_adv: "q_adv_learner"
# learner: "facmac_learner"
# double_q: True

name: "q_adv"

# --- FACMAC specific parameters ---
action_range: ~
action_selector: ~
agent: mlp
obs_agent_id: False
obs_last_action: False
agent_output_type: ~
batch_size_run: 1
batch_size: 100 #1024
buffer_size: 1000000
buffer_warmup: 1000
discretize_actions: False
double_q: False
epsilon_decay_mode: ~
# epsilon_start: ~
# epsilon_finish: ~
# epsilon_anneal_time: ~
exploration_mode: "gaussian"
start_steps: 0 # Number of steps for uniform-random action selection, before running real policy. Helps exploration.
act_noise: 1 # Stddev for Gaussian exploration noise added to policy at training time.
ou_theta: 0.15 # D
ou_sigma: 0.2 # D
ou_noise_scale: 0.3
final_ou_noise_scale: 0.
gamma: 0.99
grad_norm_clip: 0.5
learner: "facmac_learner"
learn_interval: 1
lr: 0.001
critic_lr: 0.001
td_lambda: 0.8
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
mac: cqmix_mac
mixer: "qmix"
mixing_embed_dim: 64
skip_connections: False
gated: False
hypernet_layers: 2
hypernet_embed: 64
hyper_initialization_nonzeros: 0
# name: "facmac_mamujoco"
n_runners: ~
n_train: 1
optimizer: adam # D
optimizer_epsilon: 0.01 # D
ou_stop_episode: 100 # training noise goes to zero after this episode
rnn_hidden_dim: 300
rnn_hidden_dim1: 400
run_mode: ~
runner: "parallel"
runner_scope: 'transition'
# runner: "episode"
# runner_scope: 'episodic'
# target_update_interval: ~
recurrent_critic: False
target_update_mode: "soft"
target_update_tau: 0.001
test_greedy: ~
test_interval: 4000
test_nepisode: 10
testing_on: True
t_max: 4000000
save_model: True
save_model_interval: 100000
verbose: False
weight_decay: True
weight_decay_factor: 0.0001
env_args:
  state_last_action: False # critic adds last action internally
agent_return_logits: False
q_embed_dim: 1
render: False

